apiVersion: v1
kind: Service
metadata:
  name: beam-python-sidecar
spec:
  selector:
    app: flink-taskmanager
    component: flink-taskmanager
  ports:
    - protocol: TCP
      port: 50000
      targetPort: 50000
      name: pool