apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
data:
  AWS_S3_ENDPOINT: "http://minio.default.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin"
  AWS_REGION: us-east-1
  AWS_S3_ADDRESSING_STYLE: "path"
